const technologyData = [
    { id: 1, name: "Programming", image: "image-url-1" ,isSelected: false},
    { id: 2, name: "Web Development", image: "image-url-2" ,isSelected: false},
    { id: 3, name: "Artificial Intelligence", image: "image-url-3" ,isSelected: false},
    { id: 4, name: "Machine Learning", image: "image-url-4" ,isSelected: false},
    { id: 5, name: "Data Science", image: "image-url-5" ,isSelected: false},
    { id: 6, name: "Mobile App Development", image: "image-url-6" ,isSelected: false},
    { id: 7, name: "Cybersecurity", image: "image-url-7" ,isSelected: false},
    { id: 8, name: "Network Administration", image: "image-url-8" ,isSelected: false},
    { id: 9, name: "Database Management", image: "image-url-9" ,isSelected: false},
    { id: 10, name: "Cloud Computing", image: "image-url-10" ,isSelected: false},
    { id: 11, name: "UI/UX Design", image: "image-url-11" ,isSelected: false},
    { id: 12, name: "Software Engineering", image: "image-url-12" ,isSelected: false},
    { id: 13, name: "Embedded Systems", image: "image-url-13" ,isSelected: false},
    { id: 14, name: "DevOps", image: "image-url-14" ,isSelected: false},
    { id: 15, name: "Big Data", image: "image-url-15" ,isSelected: false},
    { id: 16, name: "Internet of Things (IoT)", image: "image-url-16" ,isSelected: false},
    { id: 17, name: "Blockchain", image: "image-url-17" ,isSelected: false},
    { id: 18, name: "Virtual Reality (VR)", image: "image-url-18" ,isSelected: false},
    { id: 19, name: "Augmented Reality (AR)", image: "image-url-19" ,isSelected: false},
    { id: 20, name: "E-commerce", image: "image-url-20" ,isSelected: false},
    { id: 21, name: "Information Security", image: "image-url-21" ,isSelected: false},
    { id: 22, name: "Data Analysis", image: "image-url-22" ,isSelected: false},
    { id: 23, name: "Wireless Communication", image: "image-url-23" ,isSelected: false},
    { id: 24, name: "Art and Technology", image: "image-url-24" ,isSelected: false},
    { id: 25, name: "Computer Graphics", image: "image-url-25" ,isSelected: false},
    { id: 26, name: "Robotics", image: "image-url-26" ,isSelected: false},
    { id: 27, name: "Human-Computer Interaction", image: "image-url-27" ,isSelected: false},
    { id: 28, name: "Information Retrieval", image: "image-url-28" ,isSelected: false},
    { id: 29, name: "Web Design", image: "image-url-29" ,isSelected: false},
    { id: 30, name: "Data Visualization", image: "image-url-30" ,isSelected: false}
  ];
  
  export default technologyData;
  